# Generated by Django 4.2.8 on 2024-05-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.TextField(max_length=700, verbose_name='суть задачи')),
                ('param_term_of_execution', models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('working days', 'working days'), ('calendar days', 'calendar days'), ('weeks', 'weeks'), ('months', 'months')], max_length=150, verbose_name='параметр времени выполнения')),
                ('term_of_execution', models.IntegerField(verbose_name='время выполнения')),
                ('status', models.CharField(choices=[('new', 'new'), ('in progress', 'in progress'), ('suspended', 'suspended'), ('cancelled', 'cancelled'), ('done', 'done')], max_length=150, verbose_name='переодичность')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичность')),
                ('is_critical', models.BooleanField(default=False, verbose_name='публичность')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=700, verbose_name='суть проекта')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
